spring.application.name=Hospital_Management_System

server.port=7777
spring.datasource.url=jdbc:mysql://localhost:3306/hospital
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# spring.datasource.hikari.maximum-pool-size=10
# spring.datasource.hikari.minimum-idle=2
# spring.datasource.hikari.idle-timeout=120000
# spring.datasource.hikari.max-lifetime=300000
# spring.datasource.hikari.keepalive-time=30000
# spring.datasource.hikari.connection-timeout=60000
# spring.datasource.hikari.validation-timeout=10000
# spring.datasource.hikari.connection-test-query=SELECT 1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=admin123

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#msg91 configuration
msg91.authkey=438401AMdwnTdtm6784ec49P1
msg91.template_id=679e31fad6fc057bbf584c22
msg91.url.send=https://control.msg91.com/api/v5/otp
msg91.url.verify=https://control.msg91.com/api/v5/otp/verify
msg91.url.resend=https://control.msg91.com/api/v5/otp/retry
  
#email smtp setup smtp.gmail.com/192.168.1.35
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dinkarprasad682@gmail.com
spring.mail.password=obxbnmdzhczglepm
spring.mail.properties.mail.smtp.auth=true 
spring.mail.properties.mail.smtp.starttls.enable=true